const Erros = {
	SENHA_INVALIDA: 'SENHA_INVALIDA',
	NOME_VAZIO: 'NOME_VAZIO',
	NOME_GRANDE: 'NOME_GRANDE',
	NOME_PEQUENO: 'NOME_PEQUENO',
	NOME_SEM_SOBRENOME: 'NOME_SEM_SOBRENOME',
	NOME_CARACTERES_INVALIDOS: 'NOME_CARACTERES_INVALIDOS',
	ID_INVALIDO: 'ID_INVALIDO',
	CPF_INVALIDO: 'CPF_INVALIDO',
} as const;

export default Erros;